package com.springboot.attendance.entity;

public enum AuditAction {
    LOGIN, LOGOUT,
    VIEW_ATTENDANCE, EXPORT_REPORT,
    CREATE_SESSION, END_SESSION,
    OVERRIDE_ATTENDANCE,
    CREATE_EMBEDDING, UPDATE_EMBEDDING, DELETE_EMBEDDING,
    CREATE_STUDENT, UPDATE_STUDENT, DELETE_STUDENT,
    CREATE_USER, UPDATE_USER, DELETE_USER,
    CREATE_CLASS, UPDATE_CLASS, DELETE_CLASS,
    ACTIVATE_USER, DEACTIVATE_USER,
    RESET_PASSWORD,
    VIEW_BENCHMARK, RUN_BENCHMARK
}